services:
  - service_name: nginxd
    description: Le service nginx nécessaire à la mise en ligne des applications web accessibles sur ce noeud.
    user: root
    group: root
    volumes:
      - /root/nginx/nginx.conf:/opt/nginx.conf
      - /var/log
      - /var/cache
    pidfile: /run/nginxd.pid
    image: /root/nginx/nginx.sif
    restart: always
    after: NetworkManager.service
    requires: NetworkManager.service
    service_group: web.essential
  - service_name: gitead
    description: Gitea, l'application web pour git
    user: charles
    group: charles
    volumes:
      - /home/charles/gitea-cluster-install/data-gitea:/data/gitea
    pidfile: /home/charles/gitea.pid
    image: /data/singularity_images/gitea-1.26.4.sif
    after: NetworkManager.service
    requires: NetworkManager.service scompose-nginxd.service
    service_group: web.optional
